options:
  volume_name:
    type: string
    default: test
    description: |
      The name of the Gluster volume to create.  This will also serve as the name
      of the mount point.  Example: mount -t glusterfs server1:/test
  cluster_type:
    type: string
    default: Replicate
    description: |
      The type of volume to setup.  Replicate is sufficient for most use cases.
      Other options include: Distribute,
        Stripe,
        StripedAndReplicate,
        Disperse,
        DistributedAndStripe,
        DistributedAndReplicate,
        DistributedAndStripedAndReplicate,
        DistributedAndDisperse.
  replication_level:
    type: int
    default: 2
    description: |
      This sets how many replicas of the data should be stored in the cluster.
      Generally 2 or 3 will be fine for almost all use cases.  Greater than 3
      could be useful for read heavy uses cases.
  filesystem_type:
    type: string
    default: xfs
    description: |
      The filesystem type to use for each one of the bricks.  Can be either
      xfs, btrfs, or ext4
  splitbrain_policy:
    type: string
    default: size
    description: |
      Split brain means that the cluster can not come to consensus on which
      version of a file to serve to a client.  
      This option will automatically resolve split-brains in replica volumes
      without having to use the gluster CLI or various other hacks.  Other
      options include: ctime|mtime|size|majority.
  source:
    type: string
    default: ppa:gluster/glusterfs-3.8
    description: |
      Optional configuration to support use of additional sources such as:

        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main

      The last option should be used in conjunction with the key configuration
      option. NOTE: Changing this configuration value after your cluster is
      deployed will initiate a rolling upgrade of the servers one by one.
  key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
